require("dotenv").config();

console.log("env loaded...");
module.exports = {
	TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
	TWILIO_API_KEY: process.env.TWILIO_API_KEY,
	TWILIO_API_SECRET: process.env.TWILIO_API_SECRET,
	TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
	TWILIO_CHAT_SERVICE_SID: process.env.TWILIO_CHAT_SERVICE_SID,
	TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER,
	TWILIO_MESSAGING_SERVICE_SID: process.env.TWILIO_MESSAGING_SERVICE_SID,
	TWILIO_NOTIFICATION_SERVICE_SID: process.env.TWILIO_NOTIFICATION_SERVICE_SID,
	TWILIO_SYNC_SERVICE_SID: process.env.TWILIO_SYNC_SERVICE_SID || "default",
	PORT: process.env.PORT || 5000,
};
